import { z } from "zod";

export enum SchoolType {
  "Bednarska Szkoła Realna" = 90,
  "Biblioteki pedagogiczne" = 58,
  "Branżowa szkoła I stopnia" = 93,
  "Branżowa szkoła II stopnia" = 94,
  "Bursa" = 55,
  "Centralna Komisja Egzaminacyjna" = 107,
  "Centrum Kształcenia Praktycznego" = 45,
  "Centrum Kształcenia Zawodowego" = 96,
  "Centrum Usług Wspólnych" = 160,
  "Dom wczasów dziecięcych" = 56,
  "Fundacje" = 144,
  "Gimnazjum" = 4,
  "Gmina" = 130,
  "Inna szkoła artystyczna" = 89,
  "Izba rzemieślnicza" = 109,
  "Kolegium nauczycielskie" = 34,
  "Kolegium Pracowników Służb Społecznych" = 65,
  "Kuratorium oświaty" = 102,
  "Liceum ogólnokształcące" = 14,
  "Liceum ogólnokształcące uzupełniające dla absolwentów zasadniczych szkół zawodowych" = 17,
  "Liceum profilowane" = 15,
  "Liceum sztuk plastycznych" = 27,
  "Miasto na prawach powiatu" = 131,
  "Międzyszkolny ośrodek sportowy" = 40,
  "Minister ds. gospodarki morskiej i żeglugi śródlądowej" = 129,
  "Minister ds. kultury i dziedzictwa narodowego" = 121,
  "Minister ds. obrony" = 123,
  "Minister ds. oświaty i wychowania" = 120,
  "Minister ds. pomocy społecznej" = 124,
  "Minister ds. rolnictwa i rozwoju wsi" = 127,
  "Minister ds. sprawiedliwości" = 125,
  "Minister ds. środowiska" = 128,
  "Minister ds. wewnętrznych i administracji" = 122,
  "Minister ds. zagranicznych" = 126,
  "Młodzieżowy dom kultury" = 38,
  "Młodzieżowy Ośrodek Socjoterapii ze szkołami" = 54,
  "Młodzieżowy Ośrodek Wychowawczy" = 53,
  "Nauczycielskie Kolegium Języków Obcych" = 35,
  "Niepubliczna placówka kształcenia ustawicznego i praktycznego" = 75,
  "Niepubliczna placówka kształcenia ustawicznego i praktycznego ze szkołami" = 83,
  "Niepubliczna placówka oświatowo-wychowawcza w systemie oświaty" = 64,
  "Ognisko pracy pozaszkolnej" = 39,
  "Ogólnokształcąca szkoła baletowa" = 29,
  "Ogólnokształcąca szkoła muzyczna I stopnia" = 21,
  "Ogólnokształcąca szkoła muzyczna II stopnia" = 24,
  "Ogólnokształcąca szkoła sztuk pięknych" = 26,
  "Ogród jordanowski" = 41,
  "Okręgowa Komisja Egzaminacyjna" = 108,
  "Okręgowy ośrodek wychowawczy" = 63,
  "Organ sprawujący nadzór pedagogiczny nad zakładami poprawczymi, schroniskami dla nieletnich, rodzinnymi ośrodkami diagnostyczno-konsultacyjnymi oraz szkołami przy zakładach karnych" = 106,
  "Organizacje Społeczne inne niż wymienione" = 136,
  "Organizacje Wyznaniowe" = 140,
  "Organizacje Związkowe" = 139,
  "Osoba fizyczna" = 146,
  "Osoba Fizyczna - Pracodawca" = 150,
  "Osoba zagraniczna" = 147,
  "Ośrodek dokształcania i doskonalenia zawodowego" = 47,
  "Ośrodek Rewalidacyjno-Wychowawczy" = 52,
  "Pałac młodzieży" = 37,
  "Placówka doskonalenia nauczycieli" = 57,
  "Placówka Kształcenia Ustawicznego - bez szkół" = 74,
  "Placówka Kształcenia Ustawicznego ze szkołami" = 46,
  "Placówki artystyczne (ognisko artystyczne)" = 44,
  "Policealna szkoła muzyczna" = 91,
  "Policealna szkoła plastyczna" = 92,
  "Poradnia psychologiczno-pedagogiczna" = 48,
  "Poradnia specjalistyczna" = 49,
  "Powiat ziemski" = 132,
  "Pozaszkolna placówka specjalistyczna" = 42,
  "Poznańska szkoła chóralna" = 82,
  "Przedsiębiorstwa Osób Fizycznych" = 141,
  "Przedsiębiorstwo Państwowe" = 134,
  "Przedszkole" = 1,
  "Punkt przedszkolny" = 81,
  "Regionalna Izba Obrachunkowa" = 161,
  "Samorząd Gospodarczy i Zawodowy" = 138,
  "Samorząd województwa" = 133,
  "Samorządowa osoba prawna" = 148,
  "Schronisko dla nieletnich" = 61,
  "Specjalistyczna jednostka nadzoru" = 105,
  "Specjalny Ośrodek Szkolno-Wychowawczy" = 51,
  "Specjalny Ośrodek Wychowawczy" = 50,
  "Spółdzielnia" = 137,
  "Spółki Handlowe" = 143,
  "Stowarzyszenia" = 135,
  "Szkoła muzyczna I stopnia" = 85,
  "Szkoła muzyczna II stopnia" = 86,
  "Szkoła podstawowa" = 3,
  "Szkoła policealna" = 19,
  "Szkoła pomaturalna bibliotekarska i animatorów kultury" = 84,
  "Szkoła specjalna przysposabiająca do pracy" = 20,
  "Szkoła sztuki cyrkowej" = 31,
  "Szkoła sztuki tańca" = 87,
  "Szkolne schronisko młodzieżowe" = 43,
  "Technikum" = 16,
  "Technikum uzupełniające dla absolwentów zasadniczych szkół zawodowych" = 18,
  "Uczelnia Kościelna" = 162,
  "Uczelnia Niepubliczna" = 142,
  "Uczelnia Publiczna" = 145,
  "Zakład poprawczy" = 60,
  "Zakład poprawczy i Schronisko dla nieletnich" = 88,
  "Zasadnicza szkoła zawodowa" = 13,
  "ZEAS (zespół obsługi ekonomiczno-administracyjnej szkół)" = 104,
  "Zespół szkół i placówek oświatowych" = 100,
  "Zespół wychowania przedszkolnego" = 80,
  "Związek Rzemiosła Polskiego" = 149,
}

export const getManySchoolsSchema = z.object({
  totalCount: z.number(),
  items: z.array(
    z.object({
      id: z.number(),
      name: z.string(),
      rspo: z.number(),
      regon: z.string(),
      liquidationDate: z.string().nullable().optional(),
      creationDate: z.string().nullable().optional(),
      complexInclusionDate: z.string().nullable().optional(),
      type: z.object({
        id: z.number(),
        name: z.string(),
      }),
      leadAuthorities: z.array(
        z.object({
          id: z.number(),
          name: z.string(),
          firstName: z.string(),
          surname: z.string(),
          secondName: z.string(),
          thirdName: z.string(),
        })
      ),
      telephone: z.string(),
      website: z.string().nullable().optional(),
      email: z.string(),
      hqAddressZipCode: z.string().nullable().optional(),
      hqAddressCity: z.string().nullable().optional(),
      hqAddressBuildingNr: z.string().nullable().optional(),
      hqAddressPremisesNr: z.string().nullable().optional(),
      hqAddressStreet: z.string().nullable().optional(),
      hqAddressLocality: z
        .object({
          id: z.number(),
          name: z.string(),
        })
        .nullable()
        .optional(),
      studentsNr: z.number(),
    })
  ),
});

export const getSchoolSchema = z.object({
  id: z.number(),
  name: z.string(),
  rspo: z.number(),
  regon: z.string(),
  nip: z.string(),
  institutionType: z.object({
    id: z.number(),
    name: z.string(),
  }),
  filingMethod: z.object({
    id: z.number(),
    name: z.string(),
  }),
  publicStatus: z.object({
    id: z.number(),
    name: z.string(),
  }),
  structurePosition: z.object({
    id: z.number(),
    name: z.string(),
  }),
  specificity: z.object({
    id: z.number(),
    name: z.string(),
  }),
  category: z.object({
    id: z.number(),
    name: z.string(),
  }),
  educationStageList: z.array(
    z.object({
      id: z.number(),
      name: z.string(),
    })
  ),
  organizationalBinding: z.object({
    id: z.number(),
    name: z.string(),
  }),
  creationDate: z.string(),
  businessStartDate: z.string(),
  complexInclusionDate: z.string().nullable().optional(),
  liquidationDate: z.string().nullable().optional(),
  directorName: z.string(),
  directorSurname: z.string(),
  hasBoardingSchool: z.boolean().nullable().optional(),
  hasPeriphery: z.boolean().nullable().optional(),
  hasDotation: z.boolean().nullable().optional(),
  dataTransmittingAuthority: z.object({
    id: z.number(),
    name: z.string(),
    regon: z.string(),
    hqAddressZipCode: z.string(),
    hqAddressPostal: z.string(),
    hqAddressBuildingNr: z.string(),
    hqAddressPremiseNr: z.string(),
    hqAddressStreet: z.string(),
    hqAddressLocality: z.object({
      id: z.number(),
      name: z.string(),
    }),
    institutionType: z.object({
      id: z.number(),
      name: z.string(),
    }),
  }),
  leadAuthorities: z.array(
    z.object({
      id: z.number(),
      name: z.string(),
      firstName: z.string(),
      surname: z.string(),
      secondName: z.string(),
      thirdName: z.string(),
      institution: z.object({
        id: z.number(),
        regon: z.string(),
        telephone: z.string(),
        email: z.string(),
        website: z.string(),
        hqAddressZipCode: z.string(),
        hqAddressPostal: z.string(),
        hqAddressBuildingNr: z.string(),
        hqAddressPremiseNr: z.string(),
        hqAddressStreet: z.string(),
        hqAddressLocality: z.object({
          id: z.number(),
          name: z.string(),
        }),
      }),
    })
  ),
  hqAddressZipCode: z.string(),
  hqAddressPostal: z.string(),
  hqAddressBuildingNr: z.string(),
  hqAddressPremiseNr: z.string(),
  hqAddressStreet: z.string(),
  hqAddressLocality: z.object({
    commune: z.object({
      district: z.object({
        state: z.object({
          id: z.number(),
          name: z.string(),
        }),
        id: z.number(),
        name: z.string(),
      }),
      id: z.number(),
      name: z.string(),
    }),
    id: z.number(),
    name: z.string(),
  }),
  hqAddressGeotag: z.object({
    latitude: z.number(),
    longitude: z.number(),
  }),
  corrAddressZipCode: z.string(),
  corrAddressPostal: z.string(),
  corrAddressBuildingNr: z.string(),
  corrAddressPremiseNr: z.string(),
  corrAddressStreet: z.string(),
  corrAddressLocality: z.object({
    commune: z.object({
      district: z.object({
        state: z.object({
          id: z.number(),
          name: z.string(),
        }),
        id: z.number(),
        name: z.string(),
      }),
      id: z.number(),
      name: z.string(),
    }),
    id: z.number(),
    name: z.string(),
  }),
  telephone: z.string(),
  email: z.string(),
  website: z.string(),
  studentsNr: z.number(),
  languageList: z.array(
    z.object({
      id: z.number(),
      name: z.string(),
    })
  ),
  departmentSpecificityList: z.array(
    z.object({
      id: z.number(),
      name: z.string(),
    })
  ),
  departmentTypeList: z.array(
    z.object({
      id: z.number(),
      name: z.string(),
    })
  ),
  isEmployingTeacher: z.boolean(),
  isEmployingPsychologist: z.boolean(),
  isEmployingSpeechTherapist: z.boolean(),
});
